pipeline {
  agent any

  stages {
    stage('Clone Repository') {
      steps {
        git 'https://github.com/yourusername/sample-app.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t myapp-image docker-app'
      }
    }

    stage('Run Container') {
      steps {
        sh 'docker run -d -p 8080:80 myapp-image'
      }
    }
  }
}

